name: Hello World Workflow

on:
  push:
    branches:
      - main # Or your default branch name

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the world
        run: echo "Hello World!"
